notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label comment 

staging:
  profile: ~
  whoami: asf-staging
  subdir: content/log4php

publish:
  profile: ~
  whoami: asf-site
  subdir: content/log4php

# Small modification to trigger redeployment
#
# Thu Oct 10 20:35:53 CEST 2024
